In [ ]:
# Numpy - Numerical python - library consisiting of  multidimesional array objects and collection of routines to process 
# the array 

# The need for NumPy arises when we are working with multi-dimensional arrays. 
# The traditional array module does not support multi-dimensional arrays

# Comparison of Numpy array over List 
# https://www.geeksforgeeks.org/python-lists-vs-numpy-arrays/ 
  

# Using Numpy we can do mathematical and logical operations on array.
# Fourier transforms and routine for shape manipulation.
# Operations related to  Linear algebra and random number generation.

# Originally Python was not designed for numeric computation. 
# As people started using python for various tasks, the need for fast numeric computation arose. 
# And the Numpy was created by a group of people in 2005 to address this challenge.

# https://www.scaler.com/topics/2d-array-in-python/ 

1. Numpy array is a collection of similar data-types that are densely packed in memory. 
    A Python list can have different data-types, which puts lots of extra constraints while doing computation on it.

2. Numpy is able to divide a task into multiple subtasks and process them parallelly.
3. Numpy functions are implemented in C. Which again makes it faster compared to Python Lists.


In [1]:
import numpy as np

In [106]:
arr11 = np.array([ [1,2,3] ])

print(arr11)
print(arr11.shape)
print(arr11.ndim)
print(arr11.size) # total no of elements in array


[[1 2 3]]
(1, 3)
2
3


In [90]:
arr0 = np.array([1,2,3])
print(arr0.shape)

print(arr0.ndim)

(3,)
1


In [94]:
arr = np.array([ [1,2,3] , [4,2,5] , [9,10,11] ] )

arr

array([[ 1,  2,  3],
       [ 4,  2,  5],
       [ 9, 10, 11]])

In [4]:

print(arr)

[[1 2 3]
 [4 2 5]]


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
print(arr.shape)

(2, 3)


In [18]:
print(arr.ndim)


2


In [12]:
arr1 = np.array( [ [ [1,2,3] , [4,2,5] , [10,11,13] ]  ] )

arr1

array([[[ 1,  2,  3],
        [ 4,  2,  5],
        [10, 11, 13]]])

In [20]:
print(arr1.ndim)
print(arr1.shape)

3
(1, 3, 3)


In [16]:
arr2 = np.array( [ [ [1,2,3] , [4,2,5] , [10,11,13] ] , [ [9,8,7] , [15,12,14] ,  [20,21,22]] ]  )
                  
arr2

array([[[ 1,  2,  3],
        [ 4,  2,  5],
        [10, 11, 13]],

       [[ 9,  8,  7],
        [15, 12, 14],
        [20, 21, 22]]])

In [21]:
print(arr2.ndim)
print(arr2.shape)

3
(2, 3, 3)


In [27]:
arr4 = np.array([ [] ])

print(arr4.ndim)

2


In [81]:
arr5 = np.array( [ [   [1,2,3] , [4,5,6] ] ,  [ [0,0] , [1,1] ] ]  )
print(arr5)
print(arr5.ndim)
print(arr5.shape)
print(arr5.dtype)

[[list([1, 2, 3]) list([4, 5, 6])]
 [list([0, 0]) list([1, 1])]]
2
(2, 2)
object


C:\Users\amikumar61\AppData\Local\Temp\ipykernel_28564\4202796111.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr5 = np.array( [ [   [1,2,3] , [4,5,6] ] ,  [ [0,0] , [1,1] ] ]  )


In [79]:
arr5 = np.array( [ [   [1,2,3] , [4,5,6] ] ,  [ [0,0] , [1,1] ] ]  , dtype=object )
print(arr5)
print(arr5.ndim)
print(arr5.shape)
print(arr5.dtype)

[[list([1, 2, 3]) list([4, 5, 6])]
 [list([0, 0]) list([1, 1])]]
2
(2, 2)
object


In [82]:
arr5 = np.array( [ [   [1,2,3] , [4,5,6] ] ,  [ [0,0,0] , [1,1,1] ] ]   )

print(arr5)
print(arr5.ndim)
print(arr5.shape)

[[[1 2 3]
  [4 5 6]]

 [[0 0 0]
  [1 1 1]]]
3
(2, 2, 3)


In [64]:
lst = [2000, 3000, 4000, 5000]

arr_lst =  np.array(lst)
print(arr_lst)
print(arr_lst.ndim , arr_lst.shape , arr_lst.dtype)
arr_lst

[2000 3000 4000 5000]
1 (4,) int32


array([2000, 3000, 4000, 5000])

In [109]:
# Upcasting : 

# Python automatically converts one data type to another data type. 
# This process doesn’t need any user involvement Python promotes the conversion of lower data type, 
# for example, integer to higher data type says float to avoid data loss. 
# This type of conversion or type casting is called UpCasting

lst1 = [2000, 3000, 4000, 5000.0]
arr_lst1 =  np.array(lst1)
print(arr_lst1)
print(arr_lst1.ndim , arr_lst1.shape , arr_lst1.dtype)
arr_lst1

[2000. 3000. 4000. 5000.]
1 (4,) float64


array([2000., 3000., 4000., 5000.])

In [67]:
lst2 = [2000, 3000, 4000, 5000.0, 'amit']
arr_lst2 =  np.array(lst2)
print(arr_lst2)
print(arr_lst2.ndim , arr_lst2.shape , arr_lst2.dtype)
arr_lst2

['2000' '3000' '4000' '5000.0' 'amit']
1 (5,) <U32


array(['2000', '3000', '4000', '5000.0', 'amit'], dtype='<U32')

In [69]:
lst3 = [[2000, 3000 ] , 4000, 5000.0, 'amit']
arr_lst3 =  np.array(lst3)
print(arr_lst3)
print(arr_lst3.ndim , arr_lst3.shape , arr_lst3.dtype)
arr_lst3

[list([2000, 3000]) 4000 5000.0 'amit']
1 (4,) object


C:\Users\amikumar61\AppData\Local\Temp\ipykernel_28564\3288120288.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr_lst3 =  np.array(lst3)


array([list([2000, 3000]), 4000, 5000.0, 'amit'], dtype=object)

In [73]:
lst3 = [[2000, 3000 ] , 4000, 5000.0, 'amit']
arr_lst3 =  np.array(lst3, dtype=object)
print(arr_lst3)
print(arr_lst3.ndim , arr_lst3.shape , arr_lst3.dtype)
arr_lst3

[list([2000, 3000]) 4000 5000.0 'amit']
1 (4,) object


array([list([2000, 3000]), 4000, 5000.0, 'amit'], dtype=object)

In [114]:
#  Ways to create an array object using numpy packages 

# print(dir(np))

# np.array()
# np.ones()
# np.zeros()
# np.empty()
# np.linspace()   - Generates only 1D array 
# np.arrange()    - Generates only 1D array 
# np.random.rand*()

In [128]:
# np.empty() - Return a new array of given shape and type, without initializing entries. 

arr1 = np.empty(5)
print(arr1)
print('Array element datatype : ', arr1.dtype)
print('Shape of array :' , arr1.shape )
print('Type of  arr1 :' , type(arr1))
print('Size/ total no of elements  of array :' , arr1.size)
print('Dimension of array : ' , arr1.ndim)

[3.17249321e+180 1.61590357e+184 4.96124884e-090 5.98633990e+174
 9.98570068e-048]
Array element datatype :  float64
Shape of array : (5,)
Type of  arr1 : <class 'numpy.ndarray'>
Size/ total no of elements  of array : 5
Dimension of array :  1


In [129]:
arr2 = np.empty((5,2))   
print(arr2)
print('Array element datatype : ', arr2.dtype)
print('Shape of array :' , arr2.shape )
print('Type of  arr2 :' , type(arr2))
print('Size/ total no of elements  of array :' , arr2.size)
print('Dimension of array : ' , arr2.ndim)

[[nan  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
Array element datatype :  float64
Shape of array : (5, 2)
Type of  arr2 : <class 'numpy.ndarray'>
Size/ total no of elements  of array : 10
Dimension of array :  2


In [130]:
arr2 = np.empty((5, 2, 3))    # 3D array 
print(arr2)
print('Array element datatype : ', arr2.dtype)
print('Shape of array :' , arr2.shape )
print('Type of  arr2 :' , type(arr2))
print('Size/ total no of elements  of array :' , arr2.size)
print('Dimension of array : ' , arr2.ndim)

[[[8.94760103e-312 9.98012605e-322 0.00000000e+000]
  [0.00000000e+000 2.98891773e-032 5.02034658e+175]]

 [[9.23470432e-071 6.12262980e+169 1.76008897e-076]
  [6.34550994e-066 6.86839922e-038 2.16385130e+190]]

 [[1.94918964e-153 9.97328607e-143 1.06396443e+224]
  [1.70100503e+256 5.49109388e-143 9.30537467e+199]]

 [[3.91177819e+179 2.81185624e-033 1.43259767e+161]
  [8.84558286e+165 7.75480389e-144 5.49810101e-143]]

 [[5.58288124e-091 2.76066132e-057 8.54518750e-072]
  [4.29598672e-096 4.82337433e+228 3.67152456e-062]]]
Array element datatype :  float64
Shape of array : (5, 2, 3)
Type of  arr2 : <class 'numpy.ndarray'>
Size/ total no of elements  of array : 30
Dimension of array :  3


In [132]:
arr2 = np.ones(10)   
print(arr2)
print(arr2.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64


In [135]:
arr2 = np.ones((5,3))  
print(arr2)
print(arr2.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64


In [137]:
arr2 = np.zeros((5,5))  
print(arr2)
print(arr2.dtype , type(arr2))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64 <class 'numpy.ndarray'>


In [141]:
# np.arange([start], stop ,[step])-  Return evenly spaced values within a given interval.

# arange always gives ONLY 1D array

# return type - ndarray
# start - 0
# step - 1

arr2 = np.arange(4,10)  
print(arr2)
print(arr2.dtype , type(arr2))

[4 5 6 7 8 9]
int32 <class 'numpy.ndarray'>


In [144]:
arr2 = np.arange(10,-10, -1)  
print(arr2)
print(arr2.dtype , type(arr2))

[10  9  8  7  6  5  4  3  2  1  0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
int32 <class 'numpy.ndarray'>


In [146]:
arr2 = np.arange(10, step = 2)  
print(arr2)
print(arr2.dtype , type(arr2))

[0 2 4 6 8]
int32 <class 'numpy.ndarray'>


In [160]:
for i in np.arange(10, step = 2) :
    arr = np.array([ [i, i, i] , [i,i,i] ])

arr

array([[8, 8, 8],
       [8, 8, 8]])

In [162]:
# np.linspace() - returns an ndarray with evenly spaced values over specified interval.

# By feault it generates  50  elements which are evenly spaced over specified interval.
# np.linspace always gives ONLY 1D array

arr = np.linspace(0,10)

print(arr)
print(arr.dtype , type(arr))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
float64 <class 'numpy.ndarray'>


In [163]:
arr = np.linspace(0,10, 20)

print(arr)
print(arr.dtype , type(arr))

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
float64 <class 'numpy.ndarray'>


In [165]:
# np.random.rand*

# np.random.randint() -- # Return random integers from `low` (inclusive) to `high` (exclusive).
# 

for i in range(10):
    print(np.random.randint(6))


0
2
4
0
1
0
0
1
2
3


In [166]:
for i in range(10):
    print(np.random.randint(2, 6))  # [2,6)  -  all elements will be >= 2 and <6

4
4
4
4
5
2
5
2
2
4


In [167]:
arr = np.random.randint(2,8, 10)  # [2,8) - returns array having total 10 elments >=2 and < 8 

print(arr)
print(arr.dtype , type(arr))

[2 7 2 2 4 3 5 2 7 6]
int32 <class 'numpy.ndarray'>


In [168]:
arr = np.random.randint(2,8, (5,2))  # [2,8) - returns 2D array of 5 rows  and 2 cols having elments >=2 and < 8 

print(arr)
print(arr.dtype , type(arr))

[[3 6]
 [6 2]
 [7 3]
 [6 6]
 [3 4]]
int32 <class 'numpy.ndarray'>


In [171]:
# array using np.random.rand()

# Create an array of the given shape and populate it with
# random samples from a uniform distribution
# over ``[0, 1)``.
        
arr = np.random.rand(10)
print(arr)

print()
        
arr = np.random.rand(5,2)
print(arr)

[0.86704767 0.39395879 0.24919849 0.19505443 0.36747612 0.15683552
 0.82175698 0.12581404 0.73393668 0.44985655]

[[0.36723307 0.08812562]
 [0.72729919 0.06211933]
 [0.30855194 0.45669654]
 [0.28850735 0.38313477]
 [0.59397341 0.30157084]]


In [173]:
# array using np.random.randn()

# Return a sample (or samples) from the "standard normal"  (Gaussian) distribution.

arr = np.random.randn(5,3)
print(arr)
print()
print(arr.dtype ,  type(arr),  arr.shape , arr.size )

[[ 0.01935726  0.63921108 -0.74261273]
 [-0.19129507  2.03043567 -0.02608293]
 [ 1.20228594 -1.40609537  0.8320994 ]
 [-1.60478687 -0.23860864  0.41672348]
 [ 0.3970596  -1.36112155 -0.78634694]]

float64 <class 'numpy.ndarray'> (5, 3) 15


# Comparing List vs Array for computational speed 

In [235]:
import timeit as tt
# Time execution of a Python statement or expression 

?timeit

In [178]:

py_lst =  [  i for i in range(100000)]
start = tt.timeit()

py_lst = [i+2  for i in range(100000)]

end = tt.timeit()

print('Elapsed time : ', round((end - start) , 5))



Elapsed time :  0.00344


In [181]:
arr =  np.array([ i for i in range(100000)])
print(arr.shape, arr.ndim)

start = tt.timeit()

arr += 2 

end = tt.timeit()

print('Elapsed time : ', round((end - start) , 5))

(100000,) 1
Elapsed time :  0.00047


In [183]:
arr = np.linspace(0,10, 20)

print(arr)
print(arr.dtype , type(arr), arr.ndim)


[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
float64 <class 'numpy.ndarray'> 1


In [212]:
# Reshape() -  Returns an array containing the same data with a new shape.

arr.reshape(5,4)

arr.reshape(20,1)

array([[ 0.        ],
       [ 0.52631579],
       [ 1.05263158],
       [ 1.57894737],
       [ 2.10526316],
       [ 2.63157895],
       [ 3.15789474],
       [ 3.68421053],
       [ 4.21052632],
       [ 4.73684211],
       [ 5.26315789],
       [ 5.78947368],
       [ 6.31578947],
       [ 6.84210526],
       [ 7.36842105],
       [ 7.89473684],
       [ 8.42105263],
       [ 8.94736842],
       [ 9.47368421],
       [10.        ]])

In [213]:
np.reshape(arr, (5,4))

array([[ 0.        ,  0.52631579,  1.05263158,  1.57894737],
       [ 2.10526316,  2.63157895,  3.15789474,  3.68421053],
       [ 4.21052632,  4.73684211,  5.26315789,  5.78947368],
       [ 6.31578947,  6.84210526,  7.36842105,  7.89473684],
       [ 8.42105263,  8.94736842,  9.47368421, 10.        ]])

In [220]:
# reshape will not do the transformation on original array 

#  In Case where we are using "np.arange()"" OR "np.linspace" which always returns 1D array and our requirement is to have 
#  hihger dimension of that returned array , there we can make use of np.reshape()

print(arr)
print() 
arr1 =  np.reshape(arr , (2,5,2))

print(arr1)
print()
print(arr1.ndim , arr.shape, arr.size)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]

[[[ 0.          0.52631579]
  [ 1.05263158  1.57894737]
  [ 2.10526316  2.63157895]
  [ 3.15789474  3.68421053]
  [ 4.21052632  4.73684211]]

 [[ 5.26315789  5.78947368]
  [ 6.31578947  6.84210526]
  [ 7.36842105  7.89473684]
  [ 8.42105263  8.94736842]
  [ 9.47368421 10.        ]]]

3 (20,) 20


In [231]:
arr = np.random.rand(5,2)

# ravel()

print(arr)    #  this is 2D array , now with  the help of ravel function -- return a contiguous flattened array.;
#  however this does not change the orignal array  

print('\n\n  After applying  np.ravel() \n\n')

print(arr.ravel())

# Result  is flattened 1D array 

[[0.40352953 0.69330938]
 [0.16010646 0.80821927]
 [0.7349278  0.83580993]
 [0.10997986 0.47061429]
 [0.61403617 0.24293092]]


  After applying  np.ravel() 


[0.40352953 0.69330938 0.16010646 0.80821927 0.7349278  0.83580993
 0.10997986 0.47061429 0.61403617 0.24293092]


In [251]:
# Operations on  array  objects ..

bonus = [45000, 34000, 55000]
salary = [89000, 43000, 12000]

x = zip(bonus , salary)   

# A zip object yielding tuples until an input is exhausted. 

print(tuple(x))

[ x+y for x , y in zip(bonus, salary) ]


((45000, 89000), (34000, 43000), (55000, 12000))


[134000, 77000, 67000]

In [252]:
bonus = [45000, 34000, 55000]
salary = [89000, 43000, 12000]

print(np.array(bonus))
print(np.array(bonus))

np.array(bonus) + np.array(salary)

# Numpy  array  objects supports vector operations (in above case Element wise addtion )

[45000 34000 55000]
[45000 34000 55000]


array([134000,  77000,  67000])

In [253]:
print(2*[30000, 40000, 60000])
print(2*np.array([30000, 40000, 60000]))  # element wise multiplication

[30000, 40000, 60000, 30000, 40000, 60000]
[ 60000  80000 120000]


In [254]:
arr -arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [255]:
arr/arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [256]:
arr1 = np.array([200,  300, 400])
arr2 = np.array([2,  3 ])

arr1 * arr2  # valueError: operands could not be broadcast together with shapes (3,) (2,) 

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [257]:
arr1 = np.array([200,  300, 400])
arr2 = np.array([2,  3 , 4])

arr1 *  arr2

array([ 400,  900, 1600])

In [267]:
# Accessing elements of an array  

arr = np.arange(1,10)

print(arr)

print(arr[0])
print(arr[4])
print(arr[2])
print(arr[-1])
print(arr[-len(arr)])
print(arr[0:4]) # retrun will be array[1 2 3 4]
print(arr[:])
print(arr[-1:-3:-1])
print(arr[:4])
print(arr[4:4]) # array[]
print(arr[4:5])

[1 2 3 4 5 6 7 8 9]
1
5
3
9
1
[1 2 3 4]
[1 2 3 4 5 6 7 8 9]
[9 8]
[1 2 3 4]
[]
[5]


In [280]:
arr = np.linspace(0,10, 20).reshape(4,5)

print(arr)

print(arr[0][0])
print(arr[0,0])
print(arr[2,1])

print(arr[0][1:3])
print(arr[0,1:3])

print(arr[0:2][1:3]) #  ThiS won't work so use as below (it has range for rows as well as columns )

# NOTE : Other than  1D  indexing(chain/list indexing [i][j]) for higher dimesnions we should use Matrix indexing [i,j]

print(arr[0:2,1:3]) 


[[ 0.          0.52631579  1.05263158  1.57894737  2.10526316]
 [ 2.63157895  3.15789474  3.68421053  4.21052632  4.73684211]
 [ 5.26315789  5.78947368  6.31578947  6.84210526  7.36842105]
 [ 7.89473684  8.42105263  8.94736842  9.47368421 10.        ]]
0.0
0.0
5.789473684210526
[0.52631579 1.05263158]
[0.52631579 1.05263158]
[[2.63157895 3.15789474 3.68421053 4.21052632 4.73684211]]
[[0.52631579 1.05263158]
 [3.15789474 3.68421053]]


In [286]:
# Comparison Operator 

print(arr)

print()

print(arr > 4 )

print()


print(arr[arr > 4]) # retruns 1D array  

[[ 0.          0.52631579  1.05263158  1.57894737  2.10526316]
 [ 2.63157895  3.15789474  3.68421053  4.21052632  4.73684211]
 [ 5.26315789  5.78947368  6.31578947  6.84210526  7.36842105]
 [ 7.89473684  8.42105263  8.94736842  9.47368421 10.        ]]

[[False False False False False]
 [False False False  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]

[ 4.21052632  4.73684211  5.26315789  5.78947368  6.31578947  6.84210526
  7.36842105  7.89473684  8.42105263  8.94736842  9.47368421 10.        ]


In [6]:
# in-built methods  

# print(dir(np))
arr =  np.arange(1,11).reshape(2,5)

# np.where(condition , [x,y])   
# Returns an array with elements from `x` where `condition` is True, and elements
# from `y` elsewhere.

print("**** np.where() ****")
print(arr)
print()
print(np.where(arr > 4 , arr ,  0) ) 

# here wherever the elements satisfies the condition those are filtered 
#  and rest which do not satisfy will have value as  0 

print()

# np.max()
# Returns the indices of the maximum values along an axis. 

print("**** np.max() ****")
print(np.max(arr))  
print()

print(np.max(arr , axis = 0 ))  
print()

print(np.max(arr , axis = 1))

# np.argmax()
# Returns the indices of the maximum values along an axis.
print()
print("**** np.argmax() ****")
print(np.argmax(arr))

# np.min()
# Return the minimum of an array or minimum along an axis.

print()
print("**** np.min() ****")
print(np.min(arr))
print(np.min(arr, axis = 0))
print(np.min(arr, axis = 1))

#  np.sort(a ,) 
#  Returns a sorted copy of an array.
#  a : array_like
#      Array to be sorted.

print()
print("**** np.sort() ****")
print(np.sort([4,9,7,6]))

# np.shape()

# Return the shape of an array.
# return type is a tuple of int 
print()
print("**** np.shape() ****")
print(np.shape(arr))

# np.corrcoef() 
# The correlation coefficient matrix of the variables.
# A correlation is a relationship between two random variables basically with respect to statistics.
# A correlation coefficient is a statistical measure of the change in one variable defined by another variable.

print()
print("**** np.corrcoef() ****")
arr1 = np.arange(11,21).reshape(2,5)
print(arr1)
print()
print(np.corrcoef(arr, arr1))

# np.all()
# Test whether all array elements along a given axis evaluate to True.
# If all elements are non zero  then  np.all() returns True.

print()
print("**** np.all() ****")
print(np.all(arr))

print()

a = np.array([ [0,1,2], [2,3,1] ])
print(a)
print()
print(np.all(a))
print(np.all(a, axis = 0))
print(np.all(a, axis = 1))

a1 = np.array([ [1,1,2], [2,3,1] ])
print(a1)
print()
print(np.all(a1))


# np.any()
# Test whether any array element along a given axis evaluates to True.
# If any of the elements is non zero it will return True.

print()
print("**** np.any() ****")
print(arr)
print(np.any(arr))

arr[0,:] = 0
print(arr)
print(np.any(arr))



arr =  np.arange(1,11).reshape(2,5)
# np.mean()
# Compute the arithmetic mean along the specified axis.
 
    
print()
print("**** np.mean() ****")
print(arr)
print(np.mean(arr))
print()
print(np.mean(arr,  axis = 0)) # axis = 0  column wise 
print()
print(np.mean(arr, axis =1))  # axis = 0  row wise 

# np.std()

# np.log()

**** np.where() ****
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[ 0  0  0  0  5]
 [ 6  7  8  9 10]]

**** np.max() ****
10

[ 6  7  8  9 10]

[ 5 10]

**** np.argmax() ****
9

**** np.min() ****
1
[1 2 3 4 5]
[1 6]

**** np.sort() ****
[4 6 7 9]

**** np.shape() ****
(2, 5)

**** np.corrcoef() ****
[[11 12 13 14 15]
 [16 17 18 19 20]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

**** np.all() ****
True

[[0 1 2]
 [2 3 1]]

False
[False  True  True]
[False  True]
[[1 1 2]
 [2 3 1]]

True

**** np.any() ****
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
True
[[ 0  0  0  0  0]
 [ 6  7  8  9 10]]
True

**** np.mean() ****
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5.5

[3.5 4.5 5.5 6.5 7.5]

[3. 8.]
